name: Atualizar Playlist IPTV

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Teste
        run: echo "GitHub Actions funcionando!"
