name: Atualização IPTV Consolidada

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:

  atualizar:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Executar atualização
        run: python gerar_playlist.py

      - name: Publicar alterações
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Atualização automática da playlist IPTV
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
